### ISSUE TITLE
Cannot read properties of undefined (reading 'datamodel')

### ISSUE THREAD

**Issue by snowtorious** [morintd/prismock#545] opened 2023-08-25 04:44 UTC
Hello– I'm excited to try prismock in my NestJS project! 

Here is how I am attempting to use it:

```TypeScript
  beforeAll(async () => {
    const prismock = new PrismockClient();
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(PrismaClient)
      .useValue(prismock)
      .compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });
```
  
  However, this produces the following error:
  
  ```
  TypeError: Cannot read properties of undefined (reading 'datamodel')

      61 |
      62 |   beforeAll(async () => {
    > 63 |     const prismock = new PrismockClient();
         |                      ^
      64 |     const moduleFixture: TestingModule = await Test.createTestingModule({
      65 |       imports: [AppModule],
      66 |     })

      at Prismock.generate (../../../node_modules/prismock/src/lib/client.ts:60:85)
      at new Prismock (../../../node_modules/prismock/src/lib/client.ts:52:10)
      at src/app/app.e2e.spec.ts:63:22
      at ../../../node_modules/tslib/tslib.js:167:75
      at Object.__awaiter (../../../node_modules/tslib/tslib.js:163:16)
      at Object.<anonymous> (src/app/app.e2e.spec.ts:62:24)
```

I'd love to get this working! Am I missing something obvious?

**Comment by morintd** [comment] 2023-08-25 18:48
Hello, thanks for the support! 

Everything looks good on your side, and i'm unable to reproduce this issue locally. Using prismock in a nest project using overrideProvider works fine for me. Can you:

- Confirm you ran prisma generate before running tests?
- Let me know if you have additional configuration for prisma?
- Try to mock PrismaClient using jest.mock?
- Otherwise, create a public repository where you reproduce your bug, which I'll have a look at

**Comment by morintd** [comment] 2023-08-29 18:28
Hello @snowtorious , without answer from your side, I'll close this issue soon.

Please let me know if you found a solution

**Closed** 2023-09-02 07:47 UTC

**Comment by jomaora** [comment] 2023-12-05 14:12
Hi @morintd I'm having the same issue, but in a project not using Nest. Juste a classical Express + Apollo/GraphQL

Here is what I have in my tests...

```ts
const prismaMock = generatePrismockSync<PrismaClient>({
  models: Prisma.dmmf.datamodel.models,
}); // this works 

// but when migrating to the new class, this does not work
// const prismaMock = new PrismockClient();
```

I'm having this as error message

```sh
> nx run api.bloomers:test --testFile=packages/api.bloomers/src/__tests__/integrations/queries.spec.ts

 FAIL   api.bloomers  packages/api.bloomers/src/__tests__/integrations/queries.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'datamodel')

       5 | import { DeepMockProxy } from 'jest-mock-extended'
       6 |
    >  7 | const prismaMock = new PrismockClient();
         |                    ^
       8 |

      at Prismock.generate (../../node_modules/prismock/src/lib/client.ts:60:85)
      at new Prismock (../../node_modules/prismock/src/lib/client.ts:52:10)
      at Object.<anonymous> (src/__tests__/mocks/prisma-service.ts:7:20)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.781 s, estimated 14 s
```

regarding your questions

- _Confirm you ran prisma generate before running tests?_ Yes, my client, model and types are generated and copied to an internal module
- _Let me know if you have additional configuration for prisma?_ Nothing weird, a classical `new PrismaClient(url)` 
- _Try to mock PrismaClient using jest.mock?_ No, the ides is to use your library.

Does the new improvements are expected only for NestJS ?

**Comment by MakakWasTaken** [comment] 2024-02-07 14:14
@morintd 
I am getting the following error when trying to implement Prismock:

When using the [automatic](https://github.com/morintd/prismock?tab=readme-ov-file#automatically-recommended) approach `__mocks__/@prisma/client.ts`
```
    TypeError: Cannot read properties of undefined (reading 'dmmf')

      4 |
    > 5 | export const prisma = new PrismaClient()
        |                       ^
      6 |

      at Prismock.generate (node_modules/prismock/src/lib/client.ts:66:84)
      at new Prismock (node_modules/prismock/src/lib/client.ts:58:12)
```

When using the [PrismaClient](https://github.com/morintd/prismock?tab=readme-ov-file#prismaclient) approach
```
    TypeError: Cannot read properties of undefined (reading 'datamodel')

      4 |
    > 5 | export const prisma = new PrismaClient()
        |                       ^
      6 |

      at Prismock.generate (node_modules/prismock/src/lib/client.ts:66:89)
      at new Prismock (node_modules/prismock/src/lib/client.ts:58:12)
```

The project is running NextJS 14.1.0, Prisma 5.9.1 and Jest 29.7.0 (and Prismock 1.26.4). 
I am a bit unsure what else information would be relevant to this error. If any more is needed feel free to ask.
